language: ruby
sudo: false
install:
  - ./script/travis_cache download_bundle
  - gem install bundler
  - bundle install --without development --path=./bundle
  - bundle clean
  - ./script/travis_cache download_app
  - bundle exec rake setup
  - ./script/travis_cache upload
script:
  - bundle exec rake test_with_coveralls
rvm:
  - 1.9
  - 2.3.0
  - jruby-9.0.4.0
env:
  matrix:
    - RAILS=3.2.22
    - RAILS=4.2.5
    - RAILS="> 5.x"
  global:
    - JRUBY_OPTS="-J-Xmx1024m --debug"
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.9
      env: RAILS="> 5.x"
  allow_failures:
    - rvm: 2.3.0
      env: RAILS="> 5.x"
    - rvm: jruby-9.0.4.0
      env: RAILS="> 5.x"
branches:
  only:
    - master
